### ISSUE TITLE
Protocol not working

### ISSUE THREAD

**Issue by sajtizsolt** [turostaska/datamancy#1]
I tried to transfer my favorite Feka Fekete pictures but the protocol said I can't because he is dead. The protocol must be wrong. He can't be dead. I couldn't process his news of death, especially not after Boolean Kevinson's. Please take immediate action!

**Comment by mondokm** [comment]
😔😔😔👍 can't believe he's gone

**Comment by turostaska** [comment]
I miss him so much brehs

**Comment by sajtizsolt** [comment]
I called the support and a friendly lady (dame?) called Data Mancika helped me. It turned out that a memóriaváltas solved the problem.

**Comment by turostaska** [comment]
I'm glad that she could be of help. She's such a nice lady, I'm just puzzled why she's wearing that kerchief on her head at all times.
